/**
 * Shared directory / platform domain blocklists (single source of truth).
 *
 * Historically `candidate-classifier.service.ts` and `website-relationship.service.ts`
 * each maintained their own DIRECTORY_DOMAINS set, which drifted. Both now re-export
 * SHARED_DIRECTORY_DOMAINS from this module so a domain added here is blocked
 * everywhere (ranker third-party penalty, isUsableOfficialWebsite, relationship
 * classification, url-filter).
 *
 * Entries added for the 2026-09-24 Satungal sweep (Class A defects):
 *   - Document/presentation platforms: slideshare.net, scribd.com, docs.google.com, prezi.com, issuu.com
 *   - Ticketing/directory platforms: eticketnepal.com, yopoho.com
 */

/** Document / presentation sharing platforms — never a first-party business site. */
export const DOCUMENT_PLATFORM_DOMAINS: readonly string[] = [
  'slideshare.net',
  'scribd.com',
  'docs.google.com',
  'prezi.com',
  'issuu.com',
  'coursehero.com',
  'studocu.com',
  'slideserve.com',
  'speakerdeck.com',
];

/** Nepal ticketing / local directory platforms discovered in the Satungal sweep. */
export const EXTRA_DIRECTORY_DOMAINS: readonly string[] = [
  'eticketnepal.com',
  'yopoho.com',
  'ticketing.com.np',
  'nepalticket.com',
];

/** Historical classifier-side directory domains. */
const CLASSIFIER_HISTORICAL: readonly string[] = [
  'yellowpages.com',
  'justdial.com',
  'yelp.com',
  'signalhire.com',
  'zoominfo.com',
  'manta.com',
  'crunchbase.com',
  'foursquare.com',
  'mapquest.com',
  'nepalyp.com',
  'yellowpages.com.np',
  'dnb.com',
  'kompass.com',
  'indiamart.com',
  'tradeindia.com',
  'sulekha.com',
  'whitepages.com',
  'superpages.com',
  'bbb.org',
  'trustpilot.com',
  'sitejabber.com',
  'edusanjal.com',
  'collegesnepal.com',
  'noshnepal.com',
  'mapcarta.com',
  'restaurantguru.com',
  'usnepal.com',
  'directoryofnepal.com',
  'wikimapia.org',
  'openstreetmap.org',
  'bhansaghar.com',
  'bhansaghar.com.np',
  'skillsewa.com',
  'nepalhotel.com',
  'yandex.ru',
  'yandex.com',
  'booking.com',
  'agoda.com',
  'tripadvisor.com',
  'airbnb.com',
  'expedia.com',
  'trivago.com',
  'searchactual.com',
  'realestateinnepal.com',
  'prolinknepal.com',
  'hamrobazaar.com',
  'volza.com',
  'collegenp.com',
  'suvidhasewa.com.np',
  'aarohnepal.org',
  'virtualedufairnepal.com',
  'play.google.com',
  'apps.apple.com',
  'merokirana.com',
  'nepalhomesearch.com',
  'bihebazaar.com',
  'playo.co',
  'cybo.com',
  'turantcall.com',
  'findallnepal.com',
  'scorchdeal.com',
  'hospitalnepal.com',
  'nepalcompany.com',
  'inquirynepal.com',
  'esscobathware.com',
  'companynepal.com',
  'nepalbusinessdirectory.com',
  'biznepal.com',
  'ghargharsewa.com',
  'gamatrain.com',
  'getyourguide.com',
  'afnobazar.com.np',
  'kinbechshop.com',
  'worldtravelserver.com',
  'pasaulineskeliones.lt',
  'bizdirenepal.com',
  'ypnepal.com',
  'mysleepwell.com',
  'furniturehub.com.np',
];

/** Historical relationship-side directory domains. */
const RELATIONSHIP_HISTORICAL: readonly string[] = [
  'yellowpages.com',
  'yelp.com',
  'justdial.com',
  'signalhire.com',
  'zoominfo.com',
  'manta.com',
  'crunchbase.com',
  'dnb.com',
  'indiamart.com',
  'tradeindia.com',
  'sulekha.com',
  'booking.com',
  'tripadvisor.com',
  'agoda.com',
  'airbnb.com',
  'expedia.com',
  'trivago.com',
  'searchactual.com',
  'nepalyp.com',
  'yellowpages.com.np',
  'realestateinnepal.com',
  'edusanjal.com',
  'collegesnepal.com',
  'mapcarta.com',
  'wikimapia.org',
  'openstreetmap.org',
  'restaurantguru.com',
  'usnepal.com',
  'noshnepal.com',
  'directoryofnepal.com',
  'bhansaghar.com',
  'bhansaghar.com.np',
  'skillsewa.com',
  'nepalhotel.com',
  'yandex.ru',
  'yandex.com',
  'prolinknepal.com',
  'hamrobazaar.com',
  'volza.com',
  'collegenp.com',
  'suvidhasewa.com.np',
  'aarohnepal.org',
  'virtualedufairnepal.com',
  'merokirana.com',
  'nepalhomesearch.com',
  'bihebazaar.com',
  'playo.co',
  'cybo.com',
  'turantcall.com',
  'findallnepal.com',
  'scorchdeal.com',
  'hospitalnepal.com',
  'nepalcompany.com',
  'inquirynepal.com',
  'esscobathware.com',
  'companynepal.com',
  'nepalbusinessdirectory.com',
  'biznepal.com',
  'ghargharsewa.com',
  'gamatrain.com',
  'getyourguide.com',
  'afnobazar.com.np',
  'kinbechshop.com',
  'worldtravelserver.com',
  'pasaulineskeliones.lt',
  'bizdirenepal.com',
  'ypnepal.com',
  'mysleepwell.com',
  'furniturehub.com.np',
];

/**
 * Canonical directory/platform domain set shared by classifier, relationship,
 * ranker (via THIRD_PARTY_DOMAINS), and isUsableOfficialWebsite.
 */
export const SHARED_DIRECTORY_DOMAINS: ReadonlySet<string> = new Set<string>([
  ...CLASSIFIER_HISTORICAL,
  ...RELATIONSHIP_HISTORICAL,
  ...DOCUMENT_PLATFORM_DOMAINS,
  ...EXTRA_DIRECTORY_DOMAINS,
]);
